parser: 'babel-eslint'
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  # allow .js files to use JSX syntax
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
      - .jsx
  # no console.log in the code
  no-console:
    - error
    - allow:
      - warn
      - error
      - info
  import/resolver:
    - node
    - moduleDirectory:
      - node_modules
      - src
  jsx-a11y/anchor-is-valid:
    components: ['Link']
    specialLink: ['to']
    aspects: ['noHref', 'invalidHref', 'preferButton']
  react/prefer-stateless-function: off